// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDaefBOnr3Qey_c8yHzcgwYTytbrLg-WI',
    appId: '1:1095445876800:web:3482bc8a806158381f4fa5',
    messagingSenderId: '1095445876800',
    projectId: 'healthkranti-c34cf',
    authDomain: 'healthkranti-c34cf.firebaseapp.com',
    storageBucket: 'healthkranti-c34cf.firebasestorage.app',
    measurementId: 'G-PL6JG61J56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9V8Ij6kHLnztaut4o6Yzxgoflw9Gl3Ts',
    appId: '1:1095445876800:android:ea0d1e1ed6be20de1f4fa5',
    messagingSenderId: '1095445876800',
    projectId: 'healthkranti-c34cf',
    storageBucket: 'healthkranti-c34cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQxv3OqnOooPVA4zBx-qDEr2nwHJsIGM',
    appId: '1:1095445876800:ios:28353c95a959ff101f4fa5',
    messagingSenderId: '1095445876800',
    projectId: 'healthkranti-c34cf',
    storageBucket: 'healthkranti-c34cf.firebasestorage.app',
    iosBundleId: 'com.example.healthCure',
  );
}
